version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: sistema_pagos_db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: sistema_pagos_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sistema_pagos_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
